"""empty message

Revision ID: 1ea4d6c4b073
Revises: 4abedb145093
Create Date: 2022-01-24 22:26:35.401373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea4d6c4b073'
down_revision = '4abedb145093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcard', sa.Column('language', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcard', 'language')
    # ### end Alembic commands ###
