"""empty message

Revision ID: ebc04e9a7c05
Revises: 9867a11fea48
Create Date: 2021-12-28 17:48:29.041053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc04e9a7c05'
down_revision = '9867a11fea48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('owner_name', sa.String(), nullable=True))
    op.drop_constraint('deck_owner_id_fkey', 'deck', type_='foreignkey')
    op.create_foreign_key(None, 'deck', 'user', ['owner_name'], ['user_name'])
    op.drop_column('deck', 'owner_id')
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('deck', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deck', type_='foreignkey')
    op.create_foreign_key('deck_owner_id_fkey', 'deck', 'user', ['owner_id'], ['id'])
    op.drop_column('deck', 'owner_name')
    # ### end Alembic commands ###
